const constants = require('./config/constants');
const { buildEnvironmentConfig } = require('./environment');
const accessPolicy = require('./discord/accessPolicy');
const channel = require('./discord/channel');
const mentions = require('./discord/mentions');
const presence = require('./discord/presence');
const help = require('./commands/help');
const conversations = require('./state/conversations');
const idleChatter = require('./state/idleChatter');
const triggers = require('./ai/triggers');
const aiMentions = require('./ai/mentions');
const discordFormatting = require('./prompts/discordFormatting');
const webSearch = require('./services/webSearch');
const deepseek = require('./services/deepseek');
const gemini = require('./services/gemini');
const requestGate = require('./services/requestGate');
const bot = require('./events/bot');
const userMemory = require('./storage/userMemoryStore');

module.exports = {
  appendWebSearchSources: webSearch.appendWebSearchSources,
  appendConversationTurn: conversations.appendConversationTurn,
  appendConversationUserMessage: conversations.appendConversationUserMessage,
  appendDiscordFormattingPrompt: discordFormatting.appendDiscordFormattingPrompt,
  blockedAllowedMentions: constants.blockedAllowedMentions,
  buildBraveSearchRequest: webSearch.buildBraveSearchRequest,
  buildCurrentRequesterContextMessage: deepseek.buildCurrentRequesterContextMessage,
  buildLongTermMemoryContextMessage: deepseek.buildLongTermMemoryContextMessage,
  buildDeepSeekHeaders: deepseek.buildDeepSeekHeaders,
  buildDeepSeekPayload: deepseek.buildDeepSeekPayload,
  buildDeepSeekUrl: deepseek.buildDeepSeekUrl,
  buildGeminiHeaders: gemini.buildGeminiHeaders,
  buildGeminiPayload: gemini.buildGeminiPayload,
  buildGeminiUrl: gemini.buildGeminiUrl,
  buildEnvironmentConfig,
  DeepSeekApiError: deepseek.DeepSeekApiError,
  DeepSeekTimeoutError: deepseek.DeepSeekTimeoutError,
  GeminiApiError: gemini.GeminiApiError,
  GeminiTimeoutError: gemini.GeminiTimeoutError,
  RequestGateError: requestGate.RequestGateError,
  buildMentionRequestText: aiMentions.buildMentionRequestText,
  buildWebSearchPromptContext: webSearch.buildWebSearchPromptContext,
  buildWebSearchQuery: webSearch.buildWebSearchQuery,
  buildWebSearchRequest: webSearch.buildWebSearchRequest,
  buildReplyMentionText: aiMentions.buildReplyMentionText,
  buildSafeReplyOptions: mentions.buildSafeReplyOptions,
  buildSharedChannelContextMessage: deepseek.buildSharedChannelContextMessage,
  canReadInChannel: channel.canReadInChannel,
  canReplyInChannel: channel.canReplyInChannel,
  canReplyToMessage: channel.canReplyToMessage,
  conversationInactivityMs: constants.conversationInactivityMs,
  createAccessPolicy: accessPolicy.createAccessPolicy,
  createBotDependencies: bot.createBotDependencies,
  createConversation: conversations.createConversation,
  createRequestGate: requestGate.createRequestGate,
  createUserMemoryStore: userMemory.createUserMemoryStore,
  evaluateGuildChannelAccess: accessPolicy.evaluateGuildChannelAccess,
  evaluateMessageAccess: accessPolicy.evaluateMessageAccess,
  discordFormattingPromptMarker: discordFormatting.discordFormattingPromptMarker,
  discordFormattingPromptSuffix: discordFormatting.discordFormattingPromptSuffix,
  formatWebSearchContext: webSearch.formatWebSearchContext,
  formatWebSearchSources: webSearch.formatWebSearchSources,
  getAiHelpMessage: help.getAiHelpMessage,
  getAiHelpPages: help.getAiHelpPages,
  getHelpEmbedPages: help.getHelpEmbedPages,
  helpCatalog: help.helpCatalog,
  getRequestGateFailureMessage: requestGate.getRequestGateFailureMessage,
  getIdleChatterState: idleChatter.getIdleChatterState,
  getConversation: conversations.getConversation,
  getConversationKey: conversations.getConversationKey,
  getDeepSeekFailureMessage: deepseek.getDeepSeekFailureMessage,
  getGeminiFailureMessage: gemini.getGeminiFailureMessage,
  getMentionText: mentions.getMentionText,
  getPlainTriggerText: triggers.getPlainTriggerText,
  getWebSearchConfig: webSearch.getWebSearchConfig,
  getWebSearchConfigIssue: webSearch.getWebSearchConfigIssue,
  getWebSearchFailureMessage: webSearch.getWebSearchFailureMessage,
  getWebSearchNoResultsMessage: webSearch.getWebSearchNoResultsMessage,
  getWebSearchUnavailableMessage: webSearch.getWebSearchUnavailableMessage,
  hasExplicitInternetSearchRequest: webSearch.hasExplicitInternetSearchRequest,
  hasFreshnessTrigger: webSearch.hasFreshnessTrigger,
  isConversationExpired: conversations.isConversationExpired,
  isAiHelpCommand: help.isAiHelpCommand,
  isHelpCommand: help.isHelpCommand,
  isNewConversationCommand: triggers.isNewConversationCommand,
  isPlainTrigger: triggers.isPlainTrigger,
  isWebSearchConfigured: webSearch.isWebSearchConfigured,
  idleChatterInactivityMs: constants.idleChatterInactivityMs,
  idleChatterMessages: constants.idleChatterMessages,
  invalidateGuildIdleChatter: idleChatter.invalidateGuildIdleChatter,
  maxConversationMessages: constants.maxConversationMessages,
  MAX_MEMORY_CONTEXT_CHARACTERS: userMemory.MAX_MEMORY_CONTEXT_CHARACTERS,
  peekIdleChatterState: idleChatter.peekIdleChatterState,
  normalizeWebSearchResults: webSearch.normalizeWebSearchResults,
  normalizeAuthorMetadata: conversations.normalizeAuthorMetadata,
  readExcludedChannelIds: constants.readExcludedChannelIds,
  protectedGlazeUserIds: constants.protectedGlazeUserIds,
  recordGuildUserMessage: idleChatter.recordGuildUserMessage,
  recordGuildIdleChatterChannel: idleChatter.recordGuildIdleChatterChannel,
  factCheckClaim: deepseek.factCheckClaim,
  generateGemmaResponse: gemini.generateGemmaResponse,
  formatAuthorLabel: deepseek.formatAuthorLabel,
  normalizeFactCheckOptions: deepseek.normalizeFactCheckOptions,
  redactWebSearchQuery: webSearch.redactWebSearchQuery,
  resetChannelConversation: conversations.resetChannelConversation,
  resetConversation: conversations.resetConversation,
  resetGuildConversations: conversations.resetGuildConversations,
  replySafely: mentions.replySafely,
  replyAllowedChannelIds: constants.replyAllowedChannelIds,
  sanitizeDiscordMentions: mentions.sanitizeDiscordMentions,
  searchWeb: webSearch.searchWeb,
  setReadyPresence: presence.setReadyPresence,
  shouldRunIdleChatter: idleChatter.shouldRunIdleChatter,
  sendIdleChatter: idleChatter.sendIdleChatter,
  startGuildIdleChatterTimers: idleChatter.startGuildIdleChatterTimers,
  targetsProtectedGlazeUser: aiMentions.targetsProtectedGlazeUser,
  shouldReplyToMessage: triggers.shouldReplyToMessage,
  shouldUseInternetSearch: webSearch.shouldUseInternetSearch,
  startBot: bot.startBot,
  validateDeepSeekBaseUrl: deepseek.validateDeepSeekBaseUrl,
  validateGeminiBaseUrl: gemini.validateGeminiBaseUrl,
  wireBotEvents: bot.wireBotEvents,
};
