const constants = require('./config/constants');
const { buildEnvironmentConfig } = require('./environment');
const { getRandomYeReply, yeReplies } = require('./yeReplies');
const channel = require('./discord/channel');
const mentions = require('./discord/mentions');
const presence = require('./discord/presence');
const help = require('./commands/help');
const nn = require('./commands/nn');
const blud = require('./commands/blud');
const funmute = require('./commands/funmute');
const ratio = require('./commands/ratio');
const conversations = require('./state/conversations');
const idleChatter = require('./state/idleChatter');
const userProfiles = require('./state/userProfiles');
const rateLimits = require('./state/rateLimits');
const triggers = require('./grok/triggers');
const lore = require('./grok/lore');
const flavor = require('./grok/flavor');
const grokMentions = require('./grok/mentions');
const webSearch = require('./services/webSearch');
const deepseek = require('./services/deepseek');
const bot = require('./events/bot');

module.exports = {
  appendWebSearchSources: webSearch.appendWebSearchSources,
  appendConversationTurn: conversations.appendConversationTurn,
  appendConversationUserMessage: conversations.appendConversationUserMessage,
  applyReplyFlavor: flavor.applyReplyFlavor,
  blockedAllowedMentions: constants.blockedAllowedMentions,
  buildBraveSearchRequest: webSearch.buildBraveSearchRequest,
  buildCurrentRequesterContextMessage: deepseek.buildCurrentRequesterContextMessage,
  buildDeepSeekPayload: deepseek.buildDeepSeekPayload,
  buildEnvironmentConfig,
  buildLoreContext: lore.buildLoreContext,
  buildLoreReply: lore.buildLoreReply,
  buildUserProfilePromptContext: userProfiles.buildUserProfilePromptContext,
  buildUserProfileSummary: userProfiles.buildUserProfileSummary,
  buildUserStatsReply: userProfiles.buildUserStatsReply,
  buildWhoIsReply: lore.buildWhoIsReply,
  DeepSeekApiError: deepseek.DeepSeekApiError,
  buildMentionRequestText: grokMentions.buildMentionRequestText,
  buildWebSearchPromptContext: webSearch.buildWebSearchPromptContext,
  buildWebSearchQuery: webSearch.buildWebSearchQuery,
  buildWebSearchRequest: webSearch.buildWebSearchRequest,
  buildReplyMentionText: grokMentions.buildReplyMentionText,
  buildSafeReplyOptions: mentions.buildSafeReplyOptions,
  buildSharedChannelContextMessage: deepseek.buildSharedChannelContextMessage,
  canReadInChannel: channel.canReadInChannel,
  canReplyInChannel: channel.canReplyInChannel,
  consumeFunmuteCooldown: funmute.consumeFunmuteCooldown,
  conversationInactivityMs: constants.conversationInactivityMs,
  createConversation: conversations.createConversation,
  createUserProfile: userProfiles.createUserProfile,
  extractProfilePhrases: userProfiles.extractProfilePhrases,
  extractProfileTerms: userProfiles.extractProfileTerms,
  formatWebSearchContext: webSearch.formatWebSearchContext,
  formatWebSearchSources: webSearch.formatWebSearchSources,
  funmuteCooldownMs: funmute.funmuteCooldownMs,
  funmuteMaxDurationMs: constants.funmuteMaxDurationMs,
  getFunmuteCommandBody: funmute.getFunmuteCommandBody,
  getFunmuteDurationMs: funmute.getFunmuteDurationMs,
  getFunmuteUsageMessage: funmute.getFunmuteUsageMessage,
  getFunmuteValidationError: funmute.getFunmuteValidationError,
  getGrokHelpMessage: help.getGrokHelpMessage,
  getNnCommandText: nn.getNnCommandText,
  getNnUsageMessage: nn.getNnUsageMessage,
  getRatioUsageMessage: ratio.getRatioUsageMessage,
  getRatioValidationError: ratio.getRatioValidationError,
  getBludCommandText: blud.getBludCommandText,
  getBludUsageMessage: blud.getBludUsageMessage,
  getIdleChatterState: idleChatter.getIdleChatterState,
  getConversation: conversations.getConversation,
  getCooldownFlavor: flavor.getCooldownFlavor,
  getDeepSeekFailureMessage: deepseek.getDeepSeekFailureMessage,
  getDisplayNameForUser: lore.getDisplayNameForUser,
  getMentionText: mentions.getMentionText,
  getMonthKey: userProfiles.getMonthKey,
  getMonthlyProfileKey: userProfiles.getMonthlyProfileKey,
  getCurrentUserProfile: userProfiles.getCurrentUserProfile,
  getCurrentUserProfileSummary: userProfiles.getCurrentUserProfileSummary,
  getCurrentUserStatsReply: userProfiles.getCurrentUserStatsReply,
  getPlainGrokText: triggers.getPlainGrokText,
  getRandomYeReply,
  getRecentConversationTopicTerms: lore.getRecentConversationTopicTerms,
  getTemporaryNicknameFlavor: flavor.getTemporaryNicknameFlavor,
  getWebSearchConfig: webSearch.getWebSearchConfig,
  getWebSearchConfigIssue: webSearch.getWebSearchConfigIssue,
  getWebSearchFailureMessage: webSearch.getWebSearchFailureMessage,
  getWebSearchNoResultsMessage: webSearch.getWebSearchNoResultsMessage,
  getWebSearchRateLimitMessage: rateLimits.getWebSearchRateLimitMessage,
  getWebSearchUnavailableMessage: webSearch.getWebSearchUnavailableMessage,
  getTopMonthlyUserProfiles: userProfiles.getTopMonthlyUserProfiles,
  getTopUserProfileStatsEntries: userProfiles.getTopUserProfileStatsEntries,
  getUserSpamLevel: rateLimits.getUserSpamLevel,
  hasExplicitInternetSearchRequest: webSearch.hasExplicitInternetSearchRequest,
  hasFreshnessTrigger: webSearch.hasFreshnessTrigger,
  handleRatioCommand: ratio.handleRatioCommand,
  isUserWebSearchRateLimited: rateLimits.isUserWebSearchRateLimited,
  isConversationExpired: conversations.isConversationExpired,
  isGrokLoreCommand: lore.isGrokLoreCommand,
  isGrokStatsCommand: lore.isGrokStatsCommand,
  isGrokWhoIsCommand: lore.isGrokWhoIsCommand,
  isGrokHelpCommand: help.isGrokHelpCommand,
  isNewConversationCommand: triggers.isNewConversationCommand,
  isNnCommand: nn.isNnCommand,
  isRatioCommand: ratio.isRatioCommand,
  isBludCommand: blud.isBludCommand,
  parseBludCommand: blud.parseBludCommand,
  parseGrokWhoIsTarget: lore.parseGrokWhoIsTarget,
  isPlainGrokTrigger: triggers.isPlainGrokTrigger,
  isWebSearchConfigured: webSearch.isWebSearchConfigured,
  idleChatterInactivityMs: constants.idleChatterInactivityMs,
  idleChatterMessages: constants.idleChatterMessages,
  maxConversationMessages: constants.maxConversationMessages,
  maxProfileCounterEntries: constants.maxProfileCounterEntries,
  parseFunmuteCommand: funmute.parseFunmuteCommand,
  parseFunmuteSeconds: funmute.parseFunmuteSeconds,
  normalizeWebSearchResults: webSearch.normalizeWebSearchResults,
  normalizeAuthorMetadata: conversations.normalizeAuthorMetadata,
  readExcludedChannelIds: constants.readExcludedChannelIds,
  protectedGlazeUserIds: constants.protectedGlazeUserIds,
  recordMonthlyUserMessage: userProfiles.recordMonthlyUserMessage,
  recordGuildUserMessage: idleChatter.recordGuildUserMessage,
  recordGuildIdleChatterChannel: idleChatter.recordGuildIdleChatterChannel,
  recordUserWebSearch: rateLimits.recordUserWebSearch,
  formatAuthorLabel: deepseek.formatAuthorLabel,
  redactWebSearchQuery: webSearch.redactWebSearchQuery,
  recordUserTrigger: rateLimits.recordUserTrigger,
  resetConversation: conversations.resetConversation,
  resetExpiredMonthlyProfiles: userProfiles.resetExpiredMonthlyProfiles,
  resetFunmuteCooldown: funmute.resetFunmuteCooldown,
  removeUserReactionsFromMessage: ratio.removeUserReactionsFromMessage,
  replySafely: mentions.replySafely,
  replyAllowedChannelIds: constants.replyAllowedChannelIds,
  sanitizeDiscordMentions: mentions.sanitizeDiscordMentions,
  searchWeb: webSearch.searchWeb,
  setReadyPresence: presence.setReadyPresence,
  shouldRunIdleChatter: idleChatter.shouldRunIdleChatter,
  sendIdleChatter: idleChatter.sendIdleChatter,
  startGuildIdleChatterTimers: idleChatter.startGuildIdleChatterTimers,
  targetsProtectedGlazeUser: grokMentions.targetsProtectedGlazeUser,
  translateToGoblinMode: nn.translateToGoblinMode,
  translateToBludMode: blud.translateToBludMode,
  shouldReplyToMessage: triggers.shouldReplyToMessage,
  shouldUseInternetSearch: webSearch.shouldUseInternetSearch,
  startBot: bot.startBot,
  yeReplies,
};
